{
  "exception": {
    "internal": "An error has occurred! Try again later."
  }
}